### ISSUE TITLE
Require json0 with Browserify

### ISSUE THREAD

**Issue by ghost** [ottypes/json0#14] opened 2015-11-17 15:59 UTC
Hi,

I use ShareJS with Browserify, and I have a browser-side error:
`Error: Cannot find module 'ot-json0'`

I have verified in the source of the bundle generated by Browserify and the code of ot-json0 is here.
How can I resolve that ?

Thanks by advance,
Thomas.

**Comment by josephg** [comment] 2019-04-10 01:37
Hi! I'm sorry I didn't get back to your issue. I don't know why you were having this problem; but whenever I've tried, browserify has worked fine with this library. Since this issue is so old I'm going to close it. Please re-open this issue with an example test case if you're still having problems. (Some code which reproduces the issue + your invocation of browserify)

**Closed by josephg** 2019-04-10 01:37 UTC
